name: sudorpc_client_http_dio
description: Dio HTTP client for SudoRPC Client
version: 1.0.0
homepage: https://sudorpc.com

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  dio: ^4.0.6
  sudorpc: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
